# Generated by Django 4.0.1 on 2022-01-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Telefono',
            new_name='telefono',
        ),
    ]
